version: '3.3'

services:
  wordpress:
    image: wordpress
    restart: always
    ports:
      - 9090:80
    links:
      - db:mysql
    depends_on:
      - db
    environment:
      WORDPRESS_DB_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}

  db:
    image: mysql:5.7
    restart: always
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}

volumes:
  db_data:
